import { MangaHostInfo } from '@services/scraper/scraper.interfaces';

const MANGASEE_URL = 'https://mangasee123.com/';
const MANGASEE_GENRES = [
  'Action',
  'Adult',
  'Adventure',
  'Comedy',
  'Doujinshi',
  'Drama',
  'Ecchi',
  'Fantasy',
  'Gender Bender',
  'Harem',
  'Hentai',
  'Historical',
  'Horror',
  'Isekai',
  'Josei',
  'Lolicon',
  'Martial Arts',
  'Martial Arts  Shounen',
  'Mature',
  'Mecha',
  'Mystery',
  'Psychological',
  'Romance',
  'School Life',
  'Sci-fi',
  'Seinen',
  'Shotacon',
  'Shoujo',
  'Shoujo Ai',
  'Shounen',
  'Shounen Ai',
  'Slice of Life',
  'Smut',
  'Sports',
  'Supernatural',
  'Tragedy',
  'Yaoi',
  'Yuri',
];

const MANGASEE_SORT = ['A-Z', 'Year Released', '# of Genres'];

export const MANGASEE_INFO: MangaHostInfo = {
  host: MANGASEE_URL,
  genres: MANGASEE_GENRES,
  name: 'MangaSee',
  icon: 'https://mangasee123.com/media/favicon.png',
  hasHotMangas: true,
  hasLatestMangas: true,
  hasMangaDirectory: true,
  sort: MANGASEE_SORT,
};
