import { MangaHostFiltersInfo } from '../scraper/scraper.interfaces';
import createSchema from '@mangayomu/schema-creator';

const MANGAPARKV3_GENRES = [
  '_4_koma',
  'action',
  'adaptation',
  'adult',
  'adventure',
  'age_gap',
  'aliens',
  'animals',
  'anthology',
  'artbook',
  'bara',
  'blackmail',
  'bloody',
  'brocon_siscon',
  'cars',
  'cartoon',
  'comedy',
  'comic',
  'cooking',
  'crime',
  'crossdressing',
  'cultivation',
  'death_game',
  'degeneratemc',
  'delinquents',
  'dementia',
  'demons',
  'doujinshi',
  'drama',
  'ecchi',
  'fan_colored',
  'fantasy',
  'fetish',
  'full_color',
  'futa',
  'game',
  'gender_bender',
  'genderswap',
  'ghosts',
  'gore',
  'gyaru',
  'harem',
  'harlequin',
  'hentai',
  'historical',
  'horror',
  'imageset',
  'incest',
  'isekai',
  'josei',
  'kids',
  'loli',
  'magic',
  'magical_girls',
  'manga',
  'manhua',
  'manhwa',
  'martial_arts',
  'master_servant',
  'mature',
  'mecha',
  'medical',
  'milf',
  'military',
  'monster_girls',
  'monsters',
  'music',
  'mystery',
  'netorare',
  'ninja',
  'office_workers',
  'omegaverse',
  'oneshot',
  'parody',
  'philosophical',
  'police',
  'post_apocalyptic',
  'psychological',
  'reincarnation',
  'reverse_harem',
  'romance',
  'samurai',
  'school_life',
  'sci_fi',
  'seinen',
  'shota',
  'shoujo',
  'shoujo_ai',
  'shounen',
  'shounen_ai',
  'showbiz',
  'slice_of_life',
  'sm_bdsm',
  'smut',
  'space',
  'sports',
  'step_family',
  'super_power',
  'superhero',
  'supernatural',
  'survival',
  'teacher_student',
  'thriller',
  'time_travel',
  'traditional_games',
  'tragedy',
  'vampires',
  'video_games',
  'villainess',
  'violence',
  'virtual_reality',
  'webtoon',
  'western',
  'wuxia',
  'xianxia',
  'xuanhuan',
  'yaoi',
  'yuri',
  'zombies',
] as const;

const filters = createSchema(
  ({
    createInclusiveExclusiveFilter,
    createOptionFilter,
    createSortFilter,
    createDescription,
  }) => ({
    description: createDescription(
      'NOTE: Text search is ignored whenever filters are applied!',
    ),
    Type: createInclusiveExclusiveFilter({
      fields: [
        'Artbook',
        'Cartoon',
        'Comic',
        'Doujinshi',
        'Imageset',
        'Manga',
        'Manhuwa',
        'Manhwa',
        'Webtoon',
      ],
    }),
    'Original Language': createOptionFilter({
      options: ['Any', 'Chinese', 'English', 'Japanese', 'Korean'],
      default: 'Any',
    }),
    Status: createOptionFilter({
      options: [
        'All',
        'Pending',
        'Ongoing',
        'Completed',
        'Hiatus',
        'Cancelled',
      ],
      default: 'All',
    }),
    Chapters: createOptionFilter({
      options: [
        'All',
        '1 ~ 9',
        '10 ~ 29',
        '30 ~ 99',
        '100 ~ 199',
        '200+',
        ' 100+',
        '50+',
        '10+',
        '1+',
      ],
      default: 'All',
    }),
    'Order by': createSortFilter({
      options: ['Rating', 'Comments', 'Discuss', 'Update', 'Create', 'Name'],
      default: 'Rating',
    }),
    Genres: createInclusiveExclusiveFilter({ fields: MANGAPARKV3_GENRES }),
  }),
);

export type MangaParkV3Filter = typeof filters.schema;

export const MANGAPARKV3_INFO: MangaHostFiltersInfo<MangaParkV3Filter> = {
  filters,
  isAdult: true,
  genres: MANGAPARKV3_GENRES as any,
  hasHotMangas: true,
  hasLatestMangas: true,
  hasMangaDirectory: false,
  host: 'https://mangapark.net/',
  version: '1.1.1',
  name: 'MangaPark v3',
  icon: 'https://styles.amarkcdn.com/img/mpark/favicon.ico?v1',
};
