import { MangaHostFiltersInfo } from '../scraper/scraper.interfaces';
import createSchema from '@mangayomu/schema-creator';

const MANGAPARKV3_GENRES = [
  '4-Koma',
  'Action',
  'Adaptation',
  'Adult',
  'Adventure',
  'Aliens',
  'Animals',
  'Anthology',
  'Bloody',
  'Comedy',
  'Cooking',
  'Crossdressing',
  'Cultivation',
  'Delinquents',
  'Dementia',
  'Demons',
  'Drama',
  'Ecchi',
  'Fan-Colored',
  'Fantasy',
  'Full Color',
  'Game',
  'Gender Bender',
  'Genderswap',
  'Ghosts',
  'Gore',
  'Gyaru',
  'Harem',
  'Hentai',
  'Historical',
  'Horror',
  'Incest',
  'Isekai',
  'Josei',
  'Kids',
  'Loli',
  'Magic',
  'Magical Girls',
  'Martial Arts',
  'Mature',
  'Mecha',
  'Medical',
  'Military',
  'Monster Girls',
  'Monsters',
  'Music',
  'Mystery',
  'Netorare/NTR',
  'Ninja',
  'Office Workers',
  'Oneshot',
  'Philosophical',
  'Police',
  'Post-Apocalyptic',
  'Psychological',
  'Reincarnation',
  'Reverse Harem',
  'Romance',
  'SM/BDSM',
  'Samurai',
  'School Life',
  'Sci-Fi',
  'Seinen',
  'Shota',
  'Shoujo',
  'Shoujo ai',
  'Shounen',
  'Shounen ai',
  'Slice of Life',
  'Smut',
  'Space',
  'Sports',
  'Super Power',
  'Superhero',
  'Supernatural',
  'Survival',
  'Thriller',
  'Time Travel',
  'Traditional Games',
  'Tragedy',
  'Vampires',
  'Video Games',
  'Villainess',
  'Violence',
  'Virtual Reality',
  'Wuxia',
  'Xianxia',
  'Xuanhuan',
  'Yaoi',
  'Yuri',
  'Zombies',
  'Cars',
  'Crime',
  'Parody',
] as const;

const filters = createSchema(
  ({ createInclusiveExclusiveFilter, createOptionFilter, createSortFilter, createDescription }) => ({
    description: createDescription('NOTE: Text search is ignored whenever filters are applied!'),
    Type: createInclusiveExclusiveFilter({
      fields: ['Artbook', 'Cartoon', 'Comic', 'Doujinshi', 'Imageset', 'Manga', 'Manhuwa', 'Manhwa', 'Webtoon'],
    }),
    'Original Language': createOptionFilter({
      options: ['Any', 'Chinese', 'English', 'Japanese', 'Korean'],
      default: 'Any',
    }),
    Status: createOptionFilter({
      options: ['All', 'Pending', 'Ongoing', 'Completed', 'Hiatus', 'Cancelled'],
      default: 'All',
    }),
    Chapters: createOptionFilter({
      options: ['All', '1 ~ 9', '10 ~ 29', '30 ~ 99', '100 ~ 199', '200+', ' 100+', '50+', '10+', '1+'],
      default: 'All',
    }),
    'Order by': createSortFilter({
      options: ['Rating', 'Comments', 'Discuss', 'Update', 'Create', 'Name'],
      default: 'Rating',
    }),
    Genres: createInclusiveExclusiveFilter({ fields: MANGAPARKV3_GENRES }),
  })
);

export type MangaParkV3Filter = typeof filters.schema;

export const MANGAPARKV3_INFO: MangaHostFiltersInfo<MangaParkV3Filter> = {
  filters,
  genres: MANGAPARKV3_GENRES as any,
  hasHotMangas: true,
  hasLatestMangas: true,
  hasMangaDirectory: false,
  host: 'https://mangapark.net/',
  version: '1.1.1',
  name: 'MangaPark v3',
  icon: 'https://styles.amarkcdn.com/img/mpark/favicon.ico?v1',
};
